config/routes.rb
Rails.application.routes.draw do
  resources :new_souths

end

app/models/new_south.rb
class NewSouth < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/new_souths_controller.rb
class NewSouthsController < ApplicationController
  before_action :set_new_south, only: [:show, :edit, :update, :destroy]

  # GET /new_souths
  # GET /new_souths.json
  def index
    @new_souths = NewSouth.all
  end

  # GET /new_souths/1
  # GET /new_souths/1.json
  def show
  end

  # GET /new_souths/new
  def new
    @new_south = NewSouth.new
  end

  # GET /new_souths/1/edit
  def edit
  end

  # POST /new_souths
  # POST /new_souths.json
  def create
    @new_south = NewSouth.new(new_south_params)

    respond_to do |format|
      if @new_south.save
        format.html { redirect_to @new_south, notice: 'New south was successfully created.' }
        format.json { render :show, status: :created, location: @new_south }
      else
        format.html { render :new }
        format.json { render json: @new_south.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /new_souths/1
  # PATCH/PUT /new_souths/1.json
  def update
    respond_to do |format|
      if @new_south.update(new_south_params)
        format.html { redirect_to @new_south, notice: 'New south was successfully updated.' }
        format.json { render :show, status: :ok, location: @new_south }
      else
        format.html { render :edit }
        format.json { render json: @new_south.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /new_souths/1
  # DELETE /new_souths/1.json
  def destroy
    @new_south.destroy
    respond_to do |format|
      format.html { redirect_to new_souths_url, notice: 'New south was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_new_south
      @new_south = NewSouth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def new_south_params
      params.require(:new_south).permit(:title, :notes, :due, :done)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_souths_helper.rb
module NewSouthsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Newsouth</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/new_souths/_form.html.erb
<%= form_for(@new_south) do |f| %>
  <% if @new_south.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_south.errors.count, "error") %> prohibited this new_south from being saved:</h2>

      <ul>
      <% @new_south.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
  <div class="field">
    <%= f.label :due %><br>
    <%= f.date_select :due %>
  </div>
  <div class="field">
    <%= f.label :done %><br>
    <%= f.check_box :done %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/new_souths/edit.html.erb
<h1>Editing new_south</h1>

<%= render 'form' %>

<%= link_to 'Show', @new_south %> |
<%= link_to 'Back', new_souths_path %>

app/views/new_souths/index.html.erb
<h1>Listing new_souths</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Notes</th>
      <th>Due</th>
      <th>Done</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @new_souths.each do |new_south| %>
      <tr>
        <td><%= new_south.title %></td>
        <td><%= new_south.notes %></td>
        <td><%= new_south.due %></td>
        <td><%= new_south.done %></td>
        <td><%= link_to 'Show', new_south %></td>
        <td><%= link_to 'Edit', edit_new_south_path(new_south) %></td>
        <td><%= link_to 'Destroy', new_south, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New New south', new_new_south_path %>

app/views/new_souths/new.html.erb
<h1>New new_south</h1>

<%= render 'form' %>

<%= link_to 'Back', new_souths_path %>

app/views/new_souths/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @new_south.title %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @new_south.notes %>
</p>

<p>
  <strong>Due:</strong>
  <%= @new_south.due %>
</p>

<p>
  <strong>Done:</strong>
  <%= @new_south.done %>
</p>

<%= link_to 'Edit', edit_new_south_path(@new_south) %> |
<%= link_to 'Back', new_souths_path %>